#pragma kernel CSMain
#pragma use_dxc
#pragma require waveMath

#include "../LightingCommon.hlsl"

RWTexture2D<min16uint2> Result;

const static min16uint ThreadCount = 32u;

[numthreads(ThreadCount, 1, 1)]
void CSMain(min16uint binIndex : SV_GroupID)
{
	min16uint laneIndex = WaveGetLaneIndex();
	min16uint minIndex = 65536u;
	min16uint maxIndex = 0u;
	
	for (min16uint i = 0; i < LightIndexCount; i++)
	{
		min16uint index = i * ThreadCount + laneIndex;
		if (index >= LightCount)
			continue;
			
		Light light = PointLights[index];
			
		// Calculate min and max view depth
		float minZ = light.cullingSphere.z - light.cullingSphere.w;
		float maxZ = light.cullingSphere.z + light.cullingSphere.w;
			
		min16uint minBin = max(0u, (min16uint) (minZ * RcpBinWidth));
		min16uint maxBin = min(LightCullDepthSlices - 1u, (min16uint) (maxZ * RcpBinWidth));
		
		// Check if this bin is within the light's min+max range.
		if (binIndex < minBin || binIndex > maxBin)
			continue;
			
		minIndex = min(minIndex, index);
		maxIndex = max(maxIndex, index);
	}
	
	minIndex = WaveActiveMin(minIndex);
	maxIndex = WaveActiveMax(maxIndex);
	
	if (laneIndex)
		return;
	
	Result[min16uint2(binIndex, 0u)] = min16uint2(minIndex, maxIndex);
}
